/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Leonardo
 */
public class CadastroCandidato extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	
	/** 
	 * Creates new form CadastroCandidato 
	 */
    public CadastroCandidato() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jLabelTelaCandidato = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeCandidato = new javax.swing.JTextField();
        jLabelCandidatoSobrenome = new javax.swing.JLabel();
        jTextFieldCandidatoSobrenome = new javax.swing.JTextField();
        jButtonSalvarCandidato = new javax.swing.JButton();
        jLabelFundoCandidato = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(null);

        jLabelTelaCandidato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTelaCandidato.setText("Candidato");
        getContentPane().add(jLabelTelaCandidato);
        jLabelTelaCandidato.setBounds(170, 20, 70, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 80, 50, 30);
        getContentPane().add(jTextFieldNomeCandidato);
        jTextFieldNomeCandidato.setBounds(90, 80, 260, 30);

        jLabelCandidatoSobrenome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCandidatoSobrenome.setText("Sobrenome:");
        getContentPane().add(jLabelCandidatoSobrenome);
        jLabelCandidatoSobrenome.setBounds(30, 140, 76, 30);

        jTextFieldCandidatoSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCandidatoSobrenomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCandidatoSobrenome);
        jTextFieldCandidatoSobrenome.setBounds(120, 140, 230, 30);

        jButtonSalvarCandidato.setText("Salvar");
        getContentPane().add(jButtonSalvarCandidato);
        jButtonSalvarCandidato.setBounds(160, 220, 80, 30);

        jLabelFundoCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plano de fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoCandidato);
        jLabelFundoCandidato.setBounds(0, 0, 410, 310);

        setSize(new java.awt.Dimension(416, 331));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCandidatoSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCandidatoSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCandidatoSobrenomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
               
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCandidato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvarCandidato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCandidatoSobrenome;
    private javax.swing.JLabel jLabelFundoCandidato;
    private javax.swing.JLabel jLabelTelaCandidato;
    private javax.swing.JTextField jTextFieldCandidatoSobrenome;
    private javax.swing.JTextField jTextFieldNomeCandidato;
    // End of variables declaration//GEN-END:variables

}
