/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Leonardo
 */
public class CadastroSalas extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	
	/** 
	 * Creates new form CadastroSalas 
	 */
    public CadastroSalas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        jLabelTituloSalas = new javax.swing.JLabel();
        jLabelNomeSala = new javax.swing.JLabel();
        jTextFieldNomeSala = new javax.swing.JTextField();
        jLabelLotacaoSala = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelFundoSalas = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 322));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelTituloSalas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTituloSalas.setText("Salas");
        getContentPane().add(jLabelTituloSalas);
        jLabelTituloSalas.setBounds(190, 20, 30, 20);

        jLabelNomeSala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeSala.setText("Nome sala:");
        getContentPane().add(jLabelNomeSala);
        jLabelNomeSala.setBounds(50, 80, 70, 30);
        getContentPane().add(jTextFieldNomeSala);
        jTextFieldNomeSala.setBounds(130, 80, 210, 30);

        jLabelLotacaoSala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLotacaoSala.setText("Lota\u00E7\u00E3o:");
        getContentPane().add(jLabelLotacaoSala);
        jLabelLotacaoSala.setBounds(50, 140, 60, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(120, 140, 60, 30);

        jButton1.setText("Salvar");
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 210, 90, 30);

        jLabelFundoSalas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plano de fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoSalas);
        jLabelFundoSalas.setBounds(0, 0, 440, 310);

        setSize(new java.awt.Dimension(416, 319));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroSalas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelFundoSalas;
    private javax.swing.JLabel jLabelLotacaoSala;
    private javax.swing.JLabel jLabelNomeSala;
    private javax.swing.JLabel jLabelTituloSalas;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldNomeSala;
    // End of variables declaration//GEN-END:variables

}
