/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Leonardo
 */
public class TelaLogin extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	
	/**
     * Creates new form telaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jButtonCadastrarCandidato = new javax.swing.JButton();
        jButtonConsultaCandidato = new javax.swing.JButton();
        jLabelTituloCadastro = new javax.swing.JLabel();
        jLabelCandidato = new javax.swing.JLabel();
        jLabelSala = new javax.swing.JLabel();
        jButtonConsultaSala = new javax.swing.JButton();
        jButtonCadastrarSalas = new javax.swing.JButton();
        jLabelEspacoCafe = new javax.swing.JLabel();
        jButtonConsultaCafe = new javax.swing.JButton();
        jButtonCadastroCafe = new javax.swing.JButton();
        jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonCadastrarCandidato.setText("Cadastrar");
        jButtonCadastrarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarCandidatoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrarCandidato);
        jButtonCadastrarCandidato.setBounds(230, 130, 90, 30);

        jButtonConsultaCandidato.setText("Consulta");
        jButtonConsultaCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaCandidatoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultaCandidato);
        jButtonConsultaCandidato.setBounds(120, 130, 90, 30);

        jLabelTituloCadastro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTituloCadastro.setText("Home");
        getContentPane().add(jLabelTituloCadastro);
        jLabelTituloCadastro.setBounds(190, 20, 60, 30);

        jLabelCandidato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCandidato.setText("Candidatos");
        getContentPane().add(jLabelCandidato);
        jLabelCandidato.setBounds(180, 80, 70, 30);

        jLabelSala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSala.setText("Salas");
        getContentPane().add(jLabelSala);
        jLabelSala.setBounds(200, 170, 40, 30);

        jButtonConsultaSala.setText("Consulta");
        getContentPane().add(jButtonConsultaSala);
        jButtonConsultaSala.setBounds(120, 220, 90, 30);

        jButtonCadastrarSalas.setText("Cadastrar");
        jButtonCadastrarSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarSalasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrarSalas);
        jButtonCadastrarSalas.setBounds(230, 220, 90, 30);

        jLabelEspacoCafe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEspacoCafe.setText("Espaco caf\u00E9");
        getContentPane().add(jLabelEspacoCafe);
        jLabelEspacoCafe.setBounds(180, 260, 80, 30);

        jButtonConsultaCafe.setText("Consulta");
        getContentPane().add(jButtonConsultaCafe);
        jButtonConsultaCafe.setBounds(120, 310, 90, 30);

        jButtonCadastroCafe.setText("Cadastrar");
        jButtonCadastroCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCafeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastroCafe);
        jButtonCadastroCafe.setBounds(230, 310, 90, 30);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plano de fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(0, 0, 450, 480);

        setSize(new java.awt.Dimension(447, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarCandidatoActionPerformed
        CadastroCandidato tela = new CadastroCandidato();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarCandidatoActionPerformed

    private void jButtonCadastrarSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarSalasActionPerformed
        CadastroSalas tela2 = new CadastroSalas();
        tela2.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarSalasActionPerformed

    private void jButtonCadastroCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCafeActionPerformed
        CadastroCafe tela3 = new CadastroCafe();
        tela3.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroCafeActionPerformed

    private void jButtonConsultaCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaCandidatoActionPerformed
        ConsultaCandidatos tela4 = new ConsultaCandidatos();
        tela4.setVisible(true);
    }//GEN-LAST:event_jButtonConsultaCandidatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarCandidato;
    private javax.swing.JButton jButtonCadastrarSalas;
    private javax.swing.JButton jButtonCadastroCafe;
    private javax.swing.JButton jButtonConsultaCafe;
    private javax.swing.JButton jButtonConsultaCandidato;
    private javax.swing.JButton jButtonConsultaSala;
    private javax.swing.JLabel jLabelCandidato;
    private javax.swing.JLabel jLabelEspacoCafe;
    private javax.swing.JLabel jLabelFundoLogin;
    private javax.swing.JLabel jLabelSala;
    private javax.swing.JLabel jLabelTituloCadastro;
    // End of variables declaration//GEN-END:variables
}
